adding JARVICE support

diff --git a/Dockerfile.jarvice b/Dockerfile.jarvice
--- a/Dockerfile.jarvice
+++ b/Dockerfile.jarvice
@@ -1,21 +1,25 @@
 ARG BASE_IMAGE
-FROM ${BASE_IMAGE:-docker.io/centos/python-38-centos7:latest}
+FROM ${BASE_IMAGE:-docker.io/rockylinux:latest}
+ENV https_proxy=http://129.183.4.13:8080
+ENV http_proxy=http://129.183.4.13:8080
+ENV no_proxy=registry.smcx.local,auth.smcx.local,*.kube.local,*.atos.local,*.smcx.local,localhost,172.16.118.95/24,10.0.0.1/16,10.88.0.1/16,192.168.0.0/32,192.168.0.1/24
 
 USER root
 RUN rm -rf /data
 
-# install JARVICE Desktop
-RUN curl -k -H 'Cache-Control: no-cache' \
-        https://raw.githubusercontent.com/nimbix/image-common/master/install-nimbix.sh \
-        | bash -s -- --setup-nimbix-desktop --image-common-branch master
+#RUN curl -k -H 'Cache-Control: no-cache' \
+#        https://raw.githubusercontent.com/nimbix/image-common/master/install-nimbix.sh \
+#        | bash -s -- --setup-nimbix-desktop --image-common-branch master
 
-# Install all we need
-RUN yum install tk curl centos-release-scl -y
-RUN yum install devtoolset-8-gcc devtoolset-8-gcc-c++ -y
-SHELL [ "/usr/bin/scl", "enable", "devtoolset-8" ]
+# Install Tkinter
+RUN dnf install epel-release tk curl -y
+RUN dnf --enablerepo=epel group
+#RUN dnf config-manager --set-enabled powertools
+RUN dnf groupinstall "Xfce" "base-x" -y
 
-RUN yum install tk python3-pip python3-tkinter -y
-
+RUN dnf install xterm python3-pip python3-tkinter -y
+RUN python3 -m pip install --upgrade pip
+RUN pip3 install cython cmake scikit-build
 RUN pip3 install myqlm qiskit myqlm-interop
 
 COPY NAE/AppDef.json /etc/NAE/AppDef.json
@@ -24,3 +28,30 @@ RUN curl -k --fail -X POST -d @/etc/NAE/AppDef.json https://cloud.nimbix.net/api
 RUN bash -c 'mkdir -p /etc/NAE && touch /etc/NAE/{screenshot.png,screenshot.txt,license.txt,AppDef.json}'
 COPY qiskit-myqlm-1.py /tmp/qiskit-myqlm-1.py
 RUN chmod 777 /tmp/qiskit-myqlm-1.py
+
+RUN useradd -ms /bin/bash nimbix
+
+RUN Configfile="~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml" && \
+echo "#! /bin/bash\n\
+xdpyinfo | grep -q -i COMPOSITE || {\n\
+  echo 'x11docker/xfce: X extension COMPOSITE is missing.\n\
+Window manager compositing will not work.\n\
+If you run x11docker with option --nxagent,\n\
+you might want to add option --composite.' >&2\n\
+  [ -e $Configfile ] || {\n\
+    mkdir -p $(dirname $Configfile)\n\
+    echo '<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
+<channel name=\"xfwm4\" version=\"1.0\">\n\
+\n\
+  <property name=\"general\" type=\"empty\">\n\
+    <property name=\"use_compositing\" type=\"bool\" value=\"false\"/>\n\
+  </property>\n\
+</channel>\n\
+' > $Configfile\n\
+  }\n\
+}\n\
+startxfce4\n\
+" > /usr/local/bin/start && \
+chmod +x /usr/local/bin/start
+
+CMD start
